<a href="https://colab.research.google.com/github/arnavjune2/pytorch/blob/main/Linear_Regression_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
#Input_data
input = np.array([[32,55,77],
                  [31,75,57],
                  [52,55,77],
                  [22,100,87],
                  [62,80,77],
                  
                  ], dtype='float32')

In [3]:
#target(say we have two target)
targets = np.array([[32,66],
                    [52,76],
                    [102,155],
                    [32,26],
                    [99,100],
                    ], dtype='float32')

In [4]:
targets

array([[ 32.,  66.],
       [ 52.,  76.],
       [102., 155.],
       [ 32.,  26.],
       [ 99., 100.]], dtype=float32)

In [5]:
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    print("running on the GPU")
else:
    device = torch.device("cpu")
    print("running on the CPU")

running on the GPU


In [6]:
torch.cuda.is_available()

True

In [7]:
#to run on gpu we have to convert it into tensors
inputs = torch.from_numpy(input)
targets = torch.from_numpy(targets)

In [9]:
#initialise weights and biases
w = torch.randn(2,3, requires_grad=True)      #two outputs and 3 inputs
b = torch.randn(2, requires_grad=True) 

print(w)
print(b)

tensor([[ 1.2936,  0.4793, -1.0385],
        [-0.7294, -1.3223, -0.9279]], requires_grad=True)
tensor([1.2551, 0.9517], requires_grad=True)
