<a href="https://colab.research.google.com/github/arnavjune2/pytorch/blob/main/Linear_Regression_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import torch

In [11]:
#Input_data
input = np.array([[32,55,77],
                  [31,75,57],
                  [52,55,77],
                  [22,100,87],
                  [62,80,77],
                  
                  ], dtype='float32')

In [12]:
#target(say we have two target)
targets = np.array([[32,66],
                    [52,76],
                    [102,155],
                    [32,26],
                    [99,100],
                    ], dtype='float32')

In [13]:
targets

array([[ 32.,  66.],
       [ 52.,  76.],
       [102., 155.],
       [ 32.,  26.],
       [ 99., 100.]], dtype=float32)

In [14]:
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    print("running on the GPU")
else:
    device = torch.device("cpu")
    print("running on the CPU")

running on the GPU


In [15]:
torch.cuda.is_available()

True

In [16]:
#to run on gpu we have to convert it into tensors
inputs = torch.from_numpy(input)
targets = torch.from_numpy(targets)

In [17]:
#initialise weights and biases
w = torch.randn(2,3, requires_grad=True)      #two outputs and 3 inputs
b = torch.randn(2, requires_grad=True) 

print(w)
print(b)

tensor([[ 0.2287, -0.6534, -0.3719],
        [ 0.4003,  0.4277,  1.0429]], requires_grad=True)
tensor([ 1.0453, -0.6592], requires_grad=True)


In [18]:
def model(x):
  return x @ w.t() + b  #hypothesis  

In [19]:
preds = model(inputs)
print(preds)

tensor([[-56.2122, 115.9802],
        [-62.0704, 103.2750],
        [-51.6386, 123.9856],
        [-91.6213, 141.6536],
        [-65.6868, 138.6809]], grad_fn=<AddBackward0>)


In [21]:
#loss
def MSE(preds, target):
  diff = preds - targets
  return torch.sum(diff * diff)/ diff.numel()


In [23]:
#compute loss

loss = MSE(preds, targets)
print(loss)

tensor(10587.8047, grad_fn=<DivBackward0>)


In [24]:
#compute gradients

loss.backward()

In [25]:
print(w)
print(w.grad)

tensor([[ 0.2287, -0.6534, -0.3719],
        [ 0.4003,  0.4277,  1.0429]], requires_grad=True)
tensor([[-5455.6870, -9478.8311, -9712.0928],
        [ 1154.9482,  3549.7161,  3211.0679]])


In [26]:
with torch.no_grad():
  n = 1e-5
  w -= w.grad * n
  b -= b.grad * n

In [28]:
print(w)

tensor([[ 0.2832, -0.5586, -0.2748],
        [ 0.3887,  0.3922,  1.0108]], requires_grad=True)


In [29]:
preds = model(inputs)
print(f"loss is {MSE(preds, targets)}")

loss is 8357.1015625


In [40]:
#training
epochs = 100
n = 1e-5
for i in range(epochs):
  preds = model(inputs)
  loss = MSE(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * n
    b -= b.grad * n
    w.grad.zero_()       #clearing the gradients
    b.grad.zero_()       #clearing the gradients
  print(f"epoch: {i}, loss = {loss}")

epoch: 0, loss = 318.5791931152344
epoch: 1, loss = 318.57916259765625
epoch: 2, loss = 318.5791320800781
epoch: 3, loss = 318.5791320800781
epoch: 4, loss = 318.57916259765625
epoch: 5, loss = 318.5791320800781
epoch: 6, loss = 318.57904052734375
epoch: 7, loss = 318.57904052734375
epoch: 8, loss = 318.5790710449219
epoch: 9, loss = 318.57891845703125
epoch: 10, loss = 318.5789794921875
epoch: 11, loss = 318.5789489746094
epoch: 12, loss = 318.57891845703125
epoch: 13, loss = 318.57891845703125
epoch: 14, loss = 318.578857421875
epoch: 15, loss = 318.57891845703125
epoch: 16, loss = 318.5789489746094
epoch: 17, loss = 318.5788269042969
epoch: 18, loss = 318.57879638671875
epoch: 19, loss = 318.57879638671875
epoch: 20, loss = 318.5787658691406
epoch: 21, loss = 318.5787658691406
epoch: 22, loss = 318.5787353515625
epoch: 23, loss = 318.5787658691406
epoch: 24, loss = 318.57867431640625
epoch: 25, loss = 318.5785827636719
epoch: 26, loss = 318.5785827636719
epoch: 27, loss = 318.578643

In [41]:
preds = model(inputs)
preds

tensor([[ 46.0194,  80.9296],
        [ 51.5580,  49.7411],
        [ 85.6946, 125.4122],
        [ 26.7783,  30.9768],
        [107.5131, 128.4745]], grad_fn=<AddBackward0>)

In [42]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])