<a href="https://colab.research.google.com/github/arnavjune2/pytorch/blob/main/Linear_Regression_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import torch

In [11]:
#Input_data
input = np.array([[32,55,77],
                  [31,75,57],
                  [52,55,77],
                  [22,100,87],
                  [62,80,77],
                  
                  ], dtype='float32')

In [12]:
#target(say we have two target)
targets = np.array([[32,66],
                    [52,76],
                    [102,155],
                    [32,26],
                    [99,100],
                    ], dtype='float32')

In [13]:
targets

array([[ 32.,  66.],
       [ 52.,  76.],
       [102., 155.],
       [ 32.,  26.],
       [ 99., 100.]], dtype=float32)

In [14]:
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    print("running on the GPU")
else:
    device = torch.device("cpu")
    print("running on the CPU")

running on the GPU


In [15]:
torch.cuda.is_available()

True

In [16]:
#to run on gpu we have to convert it into tensors
inputs = torch.from_numpy(input)
targets = torch.from_numpy(targets)

In [17]:
#initialise weights and biases
w = torch.randn(2,3, requires_grad=True)      #two outputs and 3 inputs
b = torch.randn(2, requires_grad=True) 

print(w)
print(b)

tensor([[ 0.2287, -0.6534, -0.3719],
        [ 0.4003,  0.4277,  1.0429]], requires_grad=True)
tensor([ 1.0453, -0.6592], requires_grad=True)


In [18]:
def model(x):
  return x @ w.t() + b  #hypothesis  

In [19]:
preds = model(inputs)
print(preds)

tensor([[-56.2122, 115.9802],
        [-62.0704, 103.2750],
        [-51.6386, 123.9856],
        [-91.6213, 141.6536],
        [-65.6868, 138.6809]], grad_fn=<AddBackward0>)


In [21]:
#loss
def MSE(preds, target):
  diff = preds - targets
  return torch.sum(diff * diff)/ diff.numel()


In [23]:
#compute loss

loss = MSE(preds, targets)
print(loss)

tensor(10587.8047, grad_fn=<DivBackward0>)


In [24]:
#compute gradients

loss.backward()

In [25]:
print(w)
print(w.grad)

tensor([[ 0.2287, -0.6534, -0.3719],
        [ 0.4003,  0.4277,  1.0429]], requires_grad=True)
tensor([[-5455.6870, -9478.8311, -9712.0928],
        [ 1154.9482,  3549.7161,  3211.0679]])


In [26]:
with torch.no_grad():
  n = 1e-5
  w -= w.grad * n
  b -= b.grad * n

In [28]:
print(w)

tensor([[ 0.2832, -0.5586, -0.2748],
        [ 0.3887,  0.3922,  1.0108]], requires_grad=True)


In [29]:
preds = model(inputs)
print(f"loss is {MSE(preds, targets)}")

loss is 8357.1015625


In [40]:
#training
epochs = 100
n = 1e-5
for i in range(epochs):
  preds = model(inputs)
  loss = MSE(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * n
    b -= b.grad * n
    w.grad.zero_()       #clearing the gradients
    b.grad.zero_()       #clearing the gradients
  print(f"epoch: {i}, loss = {loss}")

epoch: 0, loss = 318.5791931152344
epoch: 1, loss = 318.57916259765625
epoch: 2, loss = 318.5791320800781
epoch: 3, loss = 318.5791320800781
epoch: 4, loss = 318.57916259765625
epoch: 5, loss = 318.5791320800781
epoch: 6, loss = 318.57904052734375
epoch: 7, loss = 318.57904052734375
epoch: 8, loss = 318.5790710449219
epoch: 9, loss = 318.57891845703125
epoch: 10, loss = 318.5789794921875
epoch: 11, loss = 318.5789489746094
epoch: 12, loss = 318.57891845703125
epoch: 13, loss = 318.57891845703125
epoch: 14, loss = 318.578857421875
epoch: 15, loss = 318.57891845703125
epoch: 16, loss = 318.5789489746094
epoch: 17, loss = 318.5788269042969
epoch: 18, loss = 318.57879638671875
epoch: 19, loss = 318.57879638671875
epoch: 20, loss = 318.5787658691406
epoch: 21, loss = 318.5787658691406
epoch: 22, loss = 318.5787353515625
epoch: 23, loss = 318.5787658691406
epoch: 24, loss = 318.57867431640625
epoch: 25, loss = 318.5785827636719
epoch: 26, loss = 318.5785827636719
epoch: 27, loss = 318.578643

In [41]:
preds = model(inputs)
preds

tensor([[ 46.0194,  80.9296],
        [ 51.5580,  49.7411],
        [ 85.6946, 125.4122],
        [ 26.7783,  30.9768],
        [107.5131, 128.4745]], grad_fn=<AddBackward0>)

In [42]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])

#**using torch built in functions**

In [43]:
import torch.nn as nn

In [44]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')


targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [46]:
#dataloader which will help to create batch

from torch.utils.data import TensorDataset

train_ds = TensorDataset(inputs, targets)

In [48]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [49]:
from torch.utils.data import DataLoader
batch_size =5
train_Data = DataLoader(train_ds, batch_size, shuffle=True)

In [53]:
for xb, yb in train_Data:
  print(f"inputs:  {xb}")
  print(f"target:  {yb}")

inputs:  tensor([[ 91.,  87.,  65.],
        [ 87., 135.,  57.],
        [ 68.,  97.,  70.],
        [ 73.,  67.,  43.],
        [ 73.,  66.,  44.]])
target:  tensor([[ 80., 102.],
        [118., 134.],
        [102., 120.],
        [ 56.,  70.],
        [ 57.,  69.]])
inputs:  tensor([[ 88., 134.,  59.],
        [ 69.,  96.,  70.],
        [ 68.,  96.,  71.],
        [103.,  43.,  36.],
        [101.,  44.,  37.]])
target:  tensor([[118., 132.],
        [103., 119.],
        [104., 118.],
        [ 20.,  38.],
        [ 21.,  38.]])
inputs:  tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 92.,  87.,  64.],
        [ 74.,  66.,  43.]])
target:  tensor([[119., 133.],
        [ 22.,  37.],
        [ 81., 101.],
        [ 82., 100.],
        [ 57.,  69.]])


In [54]:
#nn.linear

#define model
model = nn.Linear(3, 2 )
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1704,  0.1514,  0.4047],
        [ 0.5497,  0.3281,  0.2475]], requires_grad=True)
Parameter containing:
tensor([ 0.1517, -0.2486], requires_grad=True)


In [55]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1704,  0.1514,  0.4047],
         [ 0.5497,  0.3281,  0.2475]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1517, -0.2486], requires_grad=True)]

In [58]:
preds = model(inputs)

In [56]:
import torch.nn.functional as F
loss_fn = F.mse_loss

In [59]:
loss = loss_fn(preds, targets)

In [60]:
#optimizers

opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [73]:
#training loop
def fit(epochs, model, loss_fn, optimizer, train_data):
  for epoch in range(epochs):
    for xb, yb in train_data:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      optimizer.step()    #upgrade the weights
      optimizer.zero_grad()
    if (epoch%10)==0:
      print(f"Epoch {epoch}/{epochs} ------ Loss: {loss}")
    

In [74]:
fit(100, model, loss_fn, opt, train_Data)

Epoch 0/100 ------ Loss: 23.01542854309082
Epoch 10/100 ------ Loss: 16.42523765563965
Epoch 20/100 ------ Loss: 10.770572662353516
Epoch 30/100 ------ Loss: 18.43337631225586
Epoch 40/100 ------ Loss: 6.724353790283203
Epoch 50/100 ------ Loss: 9.617185592651367
Epoch 60/100 ------ Loss: 7.920056343078613
Epoch 70/100 ------ Loss: 9.815200805664062
Epoch 80/100 ------ Loss: 7.201103210449219
Epoch 90/100 ------ Loss: 11.452249526977539


In [76]:
pred = model(inputs)
print(pred)

tensor([[ 57.1015,  70.8652],
        [ 81.8418,  98.6405],
        [118.3504, 137.1027],
        [ 21.5450,  39.9151],
        [101.1371, 113.8341],
        [ 55.8669,  69.7672],
        [ 81.6595,  98.3423],
        [118.6265, 137.4999],
        [ 22.7796,  41.0132],
        [102.1893, 114.6339],
        [ 56.9192,  70.5670],
        [ 80.6072,  97.5424],
        [118.5327, 137.4009],
        [ 20.4927,  39.1153],
        [102.3717, 114.9321]], grad_fn=<AddmmBackward0>)


In [78]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [80]:
model(torch.tensor([[75,66,44.]]))

tensor([[56.1430, 70.1643]], grad_fn=<AddmmBackward0>)