<a href="https://colab.research.google.com/github/arnavjune2/pytorch/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("initailise")

initailise


In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0


In [ ]:
import torch

In [ ]:
#tenosrs
t1 = torch.tensor(4.)

In [ ]:
type(t1)

torch.Tensor

In [ ]:
#vectors
a = [1.,2.,3.,8.,9.]
a = torch.tensor(a)
print(a)
type(a)

tensor([1., 2., 3., 8., 9.])


torch.Tensor

In [ ]:
a.dtype

torch.float32

In [ ]:
#metrix 
t3 = torch.tensor(
    [
    [4., 5., 9.],
    [4., 5., 9.],
    [4., 5., 9.],
    ],
    requires_grad = True
)

t3

tensor([[4., 5., 9.],
        [4., 5., 9.],
        [4., 5., 9.]], requires_grad=True)

In [ ]:
print(t3)
print(t3.shape)

tensor([[4., 5., 9.],
        [4., 5., 9.],
        [4., 5., 9.]], requires_grad=True)
torch.Size([3, 3])


In [ ]:
t3 = torch.tensor(
    [
    [4., 5., 9.],
    [4., 5., 9.],
    [ 5., 9.],
    ],
    requires_grad = True
)

t3

ValueError: ignored

In [ ]:
#tenosr operations
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad= True)
b = torch.tensor(5., requires_grad= True)

x , w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# arithmetic
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward() #backpropogation

In [ ]:
print("dy/dx: " , x.grad )
print("dy/dw: " , w.grad )
print("dy/db: " , b.grad )

dy/dx:  None
dy/dw:  tensor(6.)
dy/db:  tensor(3.)


In [ ]:
#tensor function

t6 = torch.full((3,3), 9)
t6

tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])

In [ ]:
t7 = torch.cat((t3, t6))
t7

tensor([[4., 5., 9.],
        [4., 5., 9.],
        [4., 5., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]], grad_fn=<CatBackward0>)

In [ ]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.7568, -0.9589,  0.4121],
        [-0.7568, -0.9589,  0.4121],
        [-0.7568, -0.9589,  0.4121],
        [ 0.4121,  0.4121,  0.4121],
        [ 0.4121,  0.4121,  0.4121],
        [ 0.4121,  0.4121,  0.4121]], grad_fn=<SinBackward0>)

In [ ]:
t9 = t8.reshape(3,2,-1)
t9

tensor([[[-0.7568, -0.9589,  0.4121],
         [-0.7568, -0.9589,  0.4121]],

        [[-0.7568, -0.9589,  0.4121],
         [ 0.4121,  0.4121,  0.4121]],

        [[ 0.4121,  0.4121,  0.4121],
         [ 0.4121,  0.4121,  0.4121]]], grad_fn=<ReshapeAliasBackward0>)

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.
We'll leverage both these features of PyTorch extensively in this tutorial series.

In [ ]:
import numpy as np

x  = np.array([[1,2], [3,4.]])

In [ ]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)